changed name from var to real

diff --git a/.github/workflows/deploy-to-test.yml b/.github/workflows/deploy-to-test.yml
--- a/.github/workflows/deploy-to-test.yml
+++ b/.github/workflows/deploy-to-test.yml
@@ -20,10 +20,10 @@ jobs:
 
       - name: Build test image based on dev
         run: |
-          docker build --build-arg BUILD_ENV=test -t ghcr.io/${ secrets.GHCR_USERNAME }/bhs-frontend:test .
+          docker build --build-arg BUILD_ENV=test -t ghcr.io/fabianauinger/bhs-frontend:test .
 
       - name: Push test image
-        run: docker push ghcr.io/${ secrets.GHCR_USERNAME }/bhs-frontend:test
+        run: docker push ghcr.io/fabianauinger/bhs-frontend:test
 
       - name: SSH Deploy to Test Server
         uses: appleboy/ssh-action@v1.0.0
@@ -32,9 +32,9 @@ jobs:
           username: ${{ secrets.SERVER_USER }}
           key: ${{ secrets.DEPLOY_KEY }}
           script: |
-            docker pull ghcr.io/${ secrets.GHCR_USERNAME }/bhs-frontend:test || echo "Image not found, skipping pull"
+            docker pull ghcr.io/fabianauinger/bhs-frontend:test || echo "Image not found, skipping pull"
             docker stop bhs-frontend-test || true || echo "Container not running, skipping stop"
             docker rm bhs-frontend-test || true || echo "Container not found, skipping remove"
-            docker run -d --name bhs-frontend-test -p 8082:80 ghcr.io/${ secrets.GHCR_USERNAME }/bhs-frontend:test
+            docker run -d --name bhs-frontend-test -p 8082:80 ghcr.io/fabianauinger/bhs-frontend:test
 
 
